### ISSUE TITLE
[Question] How to modify the form color?

### ISSUE THREAD

**Issue by CX330Blake** [lr-m/ghidra-themes#2]
Hello, I'm currently creating a theme for Ghidra. And I'm wondering how i can modify the circled part in the graph below. Cause I don't want to see this gray thing and I want it to be the same as the main field, which is a dark purple. I know that it's because of the `lookAndFeel = Flat Dark` setting, but can I overwrite it? Thanks for your answer, it would be helpful.

![image](https://github.com/user-attachments/assets/40ed7ccd-30df-4dba-a500-ec8daa5c897f)

**Comment by lr-m** [comment]
Hey! I spent some time looking into this and it looks like it would require modification of Ghidra itself, it is a shame its a fixed colour based on the look and feel - might be worth putting an issue on the main Ghidra repo and hoping for the best.
